name: C++ CI
run-name: Build and Run Unit Tests

on:
  push:
    branches:
      - rayshaun

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: g++ TexasHoldEm\src\main\cpp\* -I TexasHoldEm\src\main\include
      - run: tree /F /A
      - uses: darenm/Setup-VSTest@v1
      - run: vstest.console TexasHoldEm\x64\Debug\TexasHoldEmTest.dll