name: C++ CI
run-name: Build and Run Unit Tests

on:
  push:
    branches:
      - rayshaun

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.5.2

      # Only run this pipeline if commit has changes in this file or in files that fit *.cpp or *.h, otherwise abort

      - uses: microsoft/setup-msbuild@v1
      - run: msbuild -maxCpuCount TexasHoldEm\TexasHoldEm.sln

      - uses: microsoft/vstest-action@v1.0.0
        with:
          testAssembly: TexasHoldEmTest.dll
          searchFolder: .\TexasHoldEm\x64\Debug\
          runInParallel: true