name: Machine Properties
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gcc -o TexasHoldEm TexasHoldEm/src/main/cpp/* -I TexasHoldEm/src/main/include/*
      - run: tree -a
      
