name: Machine Properties
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git branch -a
      - run: git diff ${{ github.ref_name }}..rayshaun
